# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 513)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"font: 12pt \"Lucida Console\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PiezaL = QtWidgets.QFrame(self.centralwidget)
        self.PiezaL.setGeometry(QtCore.QRect(30, 80, 221, 171))
        self.PiezaL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PiezaL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiezaL.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiezaL.setObjectName("PiezaL")
        self.PiezaLinvertida = QtWidgets.QFrame(self.centralwidget)
        self.PiezaLinvertida.setGeometry(QtCore.QRect(280, 80, 221, 171))
        self.PiezaLinvertida.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PiezaLinvertida.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiezaLinvertida.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiezaLinvertida.setObjectName("PiezaLinvertida")
        self.PiezaHorizontal = QtWidgets.QFrame(self.centralwidget)
        self.PiezaHorizontal.setGeometry(QtCore.QRect(530, 80, 221, 171))
        self.PiezaHorizontal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PiezaHorizontal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiezaHorizontal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiezaHorizontal.setObjectName("PiezaHorizontal")
        self.PiezaCuadrado = QtWidgets.QFrame(self.centralwidget)
        self.PiezaCuadrado.setGeometry(QtCore.QRect(30, 280, 221, 171))
        self.PiezaCuadrado.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PiezaCuadrado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiezaCuadrado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiezaCuadrado.setObjectName("PiezaCuadrado")
        self.PiezaTinvertida = QtWidgets.QFrame(self.centralwidget)
        self.PiezaTinvertida.setGeometry(QtCore.QRect(280, 280, 221, 171))
        self.PiezaTinvertida.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PiezaTinvertida.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiezaTinvertida.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiezaTinvertida.setObjectName("PiezaTinvertida")
        self.PiezaVertical = QtWidgets.QFrame(self.centralwidget)
        self.PiezaVertical.setGeometry(QtCore.QRect(530, 280, 221, 171))
        self.PiezaVertical.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PiezaVertical.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PiezaVertical.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PiezaVertical.setObjectName("PiezaVertical")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 40, 371, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 22))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        self.menuJugador = QtWidgets.QMenu(self.menuMen)
        self.menuJugador.setObjectName("menuJugador")
        self.menuColor_de_piezas = QtWidgets.QMenu(self.menuMen)
        self.menuColor_de_piezas.setObjectName("menuColor_de_piezas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTama_o_del_tablero = QtWidgets.QAction(MainWindow)
        self.actionTama_o_del_tablero.setObjectName("actionTama_o_del_tablero")
        self.actionTiempo = QtWidgets.QAction(MainWindow)
        self.actionTiempo.setObjectName("actionTiempo")
        self.actionJugador_1 = QtWidgets.QAction(MainWindow)
        self.actionJugador_1.setObjectName("actionJugador_1")
        self.actionJugador_2 = QtWidgets.QAction(MainWindow)
        self.actionJugador_2.setObjectName("actionJugador_2")
        self.actionAzul = QtWidgets.QAction(MainWindow)
        self.actionAzul.setObjectName("actionAzul")
        self.actionRojo = QtWidgets.QAction(MainWindow)
        self.actionRojo.setObjectName("actionRojo")
        self.actionAmarillo = QtWidgets.QAction(MainWindow)
        self.actionAmarillo.setObjectName("actionAmarillo")
        self.actionVerde = QtWidgets.QAction(MainWindow)
        self.actionVerde.setObjectName("actionVerde")
        self.menuJugador.addAction(self.actionJugador_1)
        self.menuJugador.addAction(self.actionJugador_2)
        self.menuColor_de_piezas.addAction(self.actionAzul)
        self.menuColor_de_piezas.addAction(self.actionRojo)
        self.menuColor_de_piezas.addAction(self.actionAmarillo)
        self.menuColor_de_piezas.addAction(self.actionVerde)
        self.menuMen.addAction(self.menuJugador.menuAction())
        self.menuMen.addAction(self.menuColor_de_piezas.menuAction())
        self.menuMen.addAction(self.actionTama_o_del_tablero)
        self.menuMen.addAction(self.actionTiempo)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Jugador", "Jugador"))
        self.label.setText(_translate("MainWindow", "Piezas que apareceran en el juego"))
        self.menuMen.setTitle(_translate("MainWindow", "Menú"))
        self.menuJugador.setTitle(_translate("MainWindow", "Jugador"))
        self.menuColor_de_piezas.setTitle(_translate("MainWindow", "Color de piezas"))
        self.actionTama_o_del_tablero.setText(_translate("MainWindow", "Tamaño del tablero"))
        self.actionTiempo.setText(_translate("MainWindow", "Tiempo"))
        self.actionJugador_1.setText(_translate("MainWindow", "Jugador 1"))
        self.actionJugador_2.setText(_translate("MainWindow", "Jugador 2"))
        self.actionAzul.setText(_translate("MainWindow", "Azul"))
        self.actionRojo.setText(_translate("MainWindow", "Rojo"))
        self.actionAmarillo.setText(_translate("MainWindow", "Amarillo"))
        self.actionVerde.setText(_translate("MainWindow", "Verde"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

