# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1320, 674)
        MainWindow.setStyleSheet("font: 12pt \"Lucida Console\";\n"
"background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tablero = QtWidgets.QFrame(self.centralwidget)
        self.Tablero.setGeometry(QtCore.QRect(20, 60, 791, 581))
        self.Tablero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tablero.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Tablero.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tablero.setObjectName("Tablero")
        self.Piezas1 = QtWidgets.QFrame(self.centralwidget)
        self.Piezas1.setGeometry(QtCore.QRect(840, 60, 211, 191))
        self.Piezas1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piezas1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Piezas1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Piezas1.setObjectName("Piezas1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(840, 30, 211, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.CoordenadaX = QtWidgets.QTextEdit(self.centralwidget)
        self.CoordenadaX.setGeometry(QtCore.QRect(980, 290, 51, 31))
        self.CoordenadaX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CoordenadaX.setObjectName("CoordenadaX")
        self.CoordenadaY = QtWidgets.QTextEdit(self.centralwidget)
        self.CoordenadaY.setGeometry(QtCore.QRect(1160, 290, 51, 31))
        self.CoordenadaY.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CoordenadaY.setObjectName("CoordenadaY")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1010, 260, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 290, 16, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1130, 290, 16, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(860, 380, 61, 21))
        self.label_6.setObjectName("label_6")
        self.Puntos1 = QtWidgets.QLabel(self.centralwidget)
        self.Puntos1.setGeometry(QtCore.QRect(980, 380, 71, 31))
        self.Puntos1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Puntos1.setText("")
        self.Puntos1.setObjectName("Puntos1")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(860, 460, 71, 21))
        self.label_8.setObjectName("label_8")
        self.Tiempo1 = QtWidgets.QLabel(self.centralwidget)
        self.Tiempo1.setGeometry(QtCore.QRect(980, 450, 71, 31))
        self.Tiempo1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tiempo1.setText("")
        self.Tiempo1.setObjectName("Tiempo1")
        self.BotonJugador1 = QtWidgets.QPushButton(self.centralwidget)
        self.BotonJugador1.setGeometry(QtCore.QRect(900, 540, 111, 31))
        self.BotonJugador1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BotonJugador1.setObjectName("BotonJugador1")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1010, 500, 151, 21))
        self.label_10.setObjectName("label_10")
        self.BotonJugador2 = QtWidgets.QPushButton(self.centralwidget)
        self.BotonJugador2.setGeometry(QtCore.QRect(1140, 540, 111, 31))
        self.BotonJugador2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BotonJugador2.setObjectName("BotonJugador2")
        self.Piezas2 = QtWidgets.QFrame(self.centralwidget)
        self.Piezas2.setGeometry(QtCore.QRect(1080, 60, 211, 191))
        self.Piezas2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Piezas2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Piezas2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Piezas2.setObjectName("Piezas2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1080, 30, 211, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(970, 340, 101, 21))
        self.label_12.setObjectName("label_12")
        self.Puntos2 = QtWidgets.QLabel(self.centralwidget)
        self.Puntos2.setGeometry(QtCore.QRect(1150, 380, 71, 31))
        self.Puntos2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Puntos2.setText("")
        self.Puntos2.setObjectName("Puntos2")
        self.Tiempo2 = QtWidgets.QLabel(self.centralwidget)
        self.Tiempo2.setGeometry(QtCore.QRect(1150, 450, 71, 31))
        self.Tiempo2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tiempo2.setText("")
        self.Tiempo2.setObjectName("Tiempo2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1140, 340, 101, 21))
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1320, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_partida = QtWidgets.QAction(MainWindow)
        self.actionAbrir_partida.setObjectName("actionAbrir_partida")
        self.actionGuardar_partida = QtWidgets.QAction(MainWindow)
        self.actionGuardar_partida.setObjectName("actionGuardar_partida")
        self.actionAyuda = QtWidgets.QAction(MainWindow)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionReportes = QtWidgets.QAction(MainWindow)
        self.actionReportes.setObjectName("actionReportes")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuMenu.addAction(self.actionAbrir_partida)
        self.menuMenu.addAction(self.actionGuardar_partida)
        self.menuMenu.addAction(self.actionAyuda)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionReportes)
        self.menuMenu.addAction(self.actionSalir)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Jugar", "Jugar"))
        self.label.setText(_translate("MainWindow", "Tablero"))
        self.label_2.setText(_translate("MainWindow", "Piezas jugador 1"))
        self.label_3.setText(_translate("MainWindow", "Coordenadas"))
        self.label_4.setText(_translate("MainWindow", "x"))
        self.label_5.setText(_translate("MainWindow", "y"))
        self.label_6.setText(_translate("MainWindow", "Puntos "))
        self.label_8.setText(_translate("MainWindow", "Tiempo"))
        self.BotonJugador1.setText(_translate("MainWindow", "Jugador 1"))
        self.label_10.setText(_translate("MainWindow", "Fin del turno"))
        self.BotonJugador2.setText(_translate("MainWindow", "Jugador 2"))
        self.label_11.setText(_translate("MainWindow", "Piezas jugador 2"))
        self.label_12.setText(_translate("MainWindow", "Jugador 1"))
        self.label_15.setText(_translate("MainWindow", "Jugador 2"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAbrir_partida.setText(_translate("MainWindow", "Abrir partida"))
        self.actionGuardar_partida.setText(_translate("MainWindow", "Guardar partida"))
        self.actionAyuda.setText(_translate("MainWindow", "Ayuda"))
        self.actionReportes.setText(_translate("MainWindow", "Reportes"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

